var elements = {
    'body_main_main': [],
    'main_aside_aside': [],
    'aside_header_headerProfile': [],
    'headerProfile_img_imgProfile': ['src__classes/images/profile.jpg'],
    'headerProfile_h2_nameProfile': ['textContent__Jose Marcelo'],
    'headerProfile_p_pProfile': ['innerHTML__Web/Application Developer <nobr>Graphic Designer</nobr>'],
    'aside_section_secAsideInfo': [],
    'secAsideInfo_article_articleContact': [],
    'articleContact_h1_titleContact': ['textContent__CONTATO'],
    'articleContact_p_contactEmail': [],
    'contactEmail_img_imgEmail': ['src__classes/images/email.svg'],
    'contactEmail_span_spanEmail': ['textContent__jmsmarcelo@live.com'],
    'secAsideInfo_article_secLang': [],
    'secLang_h1_titleLang': ['textContent__IDIOMAS'],
    'secLang_table_tabLang': [],
    'tabLang_tr_langPor': [],
    'langPor_td_namePor': ['textContent__Português: '],
    'langPor_td_levelPor': ['textContent__ Nativo'],
    'tabLang_tr_langEng': [],
    'langEng_td_nameEng': ['textContent__Inglês: '],
    'langEng_td_levelEng': ['textContent__Iniciante'],
    'main_section_secInfo': [],
    'secInfo_article_articleSkills': [],
    'articleSkills_h3_skillTitle': ['textContent__Habilidades'],
    'articleSkills_table_tableSkills': [],
    'tableSkills_tr_skillPs': [],
    'skillPs_th_skillPsName': ['textContent__Adobe Photoshop'],
    'skillPs_td_skillPsLevel': ['innerHTML__&starf;&starf;&starf;&starf;&star;'],
    'skillPs_td_skillGDicon': ['rowSpan__5'],
    'skillGDicon_img_imgSkillGDicon': ['src__classes/images/graphic-design.svg'],
    'tableSkills_tr_skillAi': [],
    'skillAi_th_skillAiName': ['textContent__Adobe Illustrator'],
    'skillAi_td_skillAiLevel': ['innerHTML__&starf;&starf;&starf;&star;&star;'],
    'tableSkills_tr_skillPr': [],
    'skillPr_th_skillPrName': ['textContent__Adobe Premiere'],
    'skillPr_td_skillPrLevel': ['innerHTML__&starf;&starf;&starf;&star;&star;'],
    'tableSkills_tr_skillAe': [],
    'skillAe_th_skillAeName': ['textContent__Adobe After Effects'],
    'skillAe_td_skillAeLevel': ['innerHTML__&starf;&starf;&star;&star;&star;'],
    'tableSkills_tr_skillAu': [],
    'skillAu_th_skillAuName': ['textContent__Adobe Audition'],
    'skillAu_td_skillAuLevel': ['innerHTML__&starf;&starf;&star;&star;&star;'],
    'tableSkills_tr_trLine': [],
    'trLine_td_tdLine': ['colSpan__3'],
    'tdLine_hr_hrLine': [],
    'tableSkills_tr_skillHTML': [],
    'skillHTML_th_skillHTMLName': ['textContent__HTML'],
    'skillHTML_td_skillHTMLLevel': ['innerHTML__&starf;&starf;&starf;&starf;&star;'],
    'skillHTML_td_skillWDicon': ['rowSpan__7'],
    'skillWDicon_img_imgSkillWDicon': ['src__classes/images/web-design.svg'],
    'tableSkills_tr_skillCSS': [],
    'skillCSS_th_skillCSSName': ['textContent__CSS'],
    'skillCSS_td_skillCSSLevel': ['innerHTML__&starf;&starf;&star;&star;&star;'],
    'tableSkills_tr_skillJs': [],
    'skillJs_th_skillJsName': ['textContent__JavaScript'],
    'skillJs_td_skillPHPLevel': ['innerHTML__&starf;&starf;&starf;&starf;&star;'],
    'tableSkills_tr_skillPHP': [],
    'skillPHP_th_skillPHPName': ['textContent__PHP'],
    'skillPHP_td_skillPHPLevel': ['innerHTML__&starf;&starf;&starf;&star;&star;'],
    'tableSkills_tr_skillJavaD': [],
    'skillJavaD_th_skillJavaDName': ['textContent__Java/Desktop'],
    'skillJavaD_td_skillJavaDLevel': ['innerHTML__&starf;&starf;&starf;&star;&star;'],
    'tableSkills_tr_skillJavaM': [],
    'skillJavaM_th_skillJavaMName': ['textContent__Java/Mobile'],
    'skillJavaM_td_skillJavaMLevel': ['innerHTML__&starf;&starf;&star;&star;&star;'],
    'tableSkills_tr_skillMySQL': [],
    'skillMySQL_th_skillMySQLName': ['textContent__MySQL'],
    'skillMySQL_td_skillMySQLLevel': ['innerHTML__&starf;&starf;&starf;&star;&star;'],
    'secInfo_hr_lineOne': [],
    'secInfo_article_articleCert': [],
    'articleCert_h3_certTitle': ['textContent__Certificações'],
    'articleCert_div_divCert': [],
    'divCert_p_beginPro': [],
    'beginPro_span_beginProdesc': ['textContent__Iniciante em Programação - '],
    'beginPro_a_beginProcert': [
        'href__https://cursos.alura.com.br/user/jmsmarcelo/degree-logica-de-programacao-turma-5-oracle-one-561815/certificate',
        'target___blank',
        'textContent__Certificado Alura'],
    'divCert_p_javaSpringB': [],
    'javaSpringB_span_javaSpringBdesc': ['textContent__Java e Spring Boot 3 - '],
    'javaSpringB_a_javaSpringBcert': [
        'href__https://cursos.alura.com.br/user/jmsmarcelo/degree-spring-framework-turma5-one-582698/certificate',
        'target___blank',
        'textContent__Certificado Alura'],
    'divCert_p_SQL': [],
    'SQL_span_SQLdesc': ['textContent__SQL com MySQL - '],
    'SQL_a_SQLcert': [
        'href__https://cursos.alura.com.br/user/jmsmarcelo/degree-oracle-mysql-3983/certificate',
        'target___blank',
        'textContent__Certificado Alura']
}