var elements = {
    'body_main_main': [],
    'main_aside_aside': [],
    'aside_header_headerProfile': [],
    'headerProfile_img_imgProfile': ['src__classes/images/profile.jpg'],
    'headerProfile_h2_nameProfile': ['textContent__Jose Marcelo'],
    'headerProfile_p_pProfile': ['innerHTML__Web/Application Developer <nobr>Graphic Designer</nobr>'],
    'aside_section_secAsideInfo': [],
    'secAsideInfo_article_articleContact': [],
    'articleContact_h1_titleContact': ['textContent__CONTATO'],
    'articleContact_p_contactEmail': [],
    'contactEmail_img_imgEmail': ['src__classes/images/email.svg'],
    'contactEmail_span_spanEmail': ['textContent__jmsmarcelo@live.com'],
    'secAsideInfo_article_secLang': [],
    'secLang_h1_titleLang': ['textContent__IDIOMAS'],
    'secLang_table_tabLang': [],
    'tabLang_tr_langPor': [],
    'langPor_td_namePor': ['textContent__Português: '],
    'langPor_td_levelPor': ['textContent__ Nativo'],
    'tabLang_tr_langEng': [],
    'langEng_td_nameEng': ['textContent__Inglês: '],
    'langEng_td_levelEng': ['textContent__Iniciante'],
    'main_section_secInfo': [],
    'secInfo_article_articleSkills': [],
    'articleSkills_h3_skillTitle': ['textContent__HABILIDADES'],
    'articleSkills_table_tableSkills': [],
    'tableSkills_tr_skillPs': [],
    'skillPs_th_skillPsName': ['textContent__Adobe Photoshop'],
    'skillPs_td_skillPsLevel': ['innerHTML__&starf;&starf;&starf;&starf;&star;'],
    'skillPs_td_skillGDicon': ['rowSpan__5'],
    'skillGDicon_img_imgSkillGDicon': ['src__classes/images/graphic-design.svg'],
    'tableSkills_tr_skillAi': [],
    'skillAi_th_skillAiName': ['textContent__Adobe Illustrator'],
    'skillAi_td_skillAiLevel': ['innerHTML__&starf;&starf;&starf;&star;&star;'],
    'tableSkills_tr_skillPr': [],
    'skillPr_th_skillPrName': ['textContent__Adobe Premiere'],
    'skillPr_td_skillPrLevel': ['innerHTML__&starf;&starf;&starf;&star;&star;'],
    'tableSkills_tr_skillAe': [],
    'skillAe_th_skillAeName': ['textContent__Adobe After Effects'],
    'skillAe_td_skillAeLevel': ['innerHTML__&starf;&starf;&star;&star;&star;'],
    'tableSkills_tr_skillAu': [],
    'skillAu_th_skillAuName': ['textContent__Adobe Audition'],
    'skillAu_td_skillAuLevel': ['innerHTML__&starf;&starf;&star;&star;&star;'],
    'tableSkills_tr_trLine': [],
    'trLine_td_tdLine': ['colSpan__3'],
    'tdLine_hr_hrLine': [],
    'tableSkills_tr_skillHTML': [],
    'skillHTML_th_skillHTMLName': ['textContent__HTML'],
    'skillHTML_td_skillHTMLLevel': ['innerHTML__&starf;&starf;&starf;&starf;&star;'],
    'skillHTML_td_skillWDicon': ['rowSpan__7'],
    'skillWDicon_img_imgSkillWDicon': ['src__classes/images/web-design.svg'],
    'tableSkills_tr_skillCSS': [],
    'skillCSS_th_skillCSSName': ['textContent__CSS'],
    'skillCSS_td_skillCSSLevel': ['innerHTML__&starf;&starf;&star;&star;&star;'],
    'tableSkills_tr_skillJs': [],
    'skillJs_th_skillJsName': ['textContent__JavaScript'],
    'skillJs_td_skillPHPLevel': ['innerHTML__&starf;&starf;&starf;&starf;&star;'],
    'tableSkills_tr_skillPHP': [],
    'skillPHP_th_skillPHPName': ['textContent__PHP'],
    'skillPHP_td_skillPHPLevel': ['innerHTML__&starf;&starf;&starf;&star;&star;'],
    'tableSkills_tr_skillJavaD': [],
    'skillJavaD_th_skillJavaDName': ['textContent__Java/Desktop'],
    'skillJavaD_td_skillJavaDLevel': ['innerHTML__&starf;&starf;&starf;&star;&star;'],
    'tableSkills_tr_skillJavaM': [],
    'skillJavaM_th_skillJavaMName': ['textContent__Java/Mobile'],
    'skillJavaM_td_skillJavaMLevel': ['innerHTML__&starf;&starf;&star;&star;&star;'],
    'tableSkills_tr_skillMySQL': [],
    'skillMySQL_th_skillMySQLName': ['textContent__MySQL'],
    'skillMySQL_td_skillMySQLLevel': ['innerHTML__&starf;&starf;&starf;&star;&star;'],
    'secInfo_hr_lineOne': [],
    'secInfo_article_articleCert': [],
    'articleCert_h3_certTitle': ['textContent__CERTIFICAÇÕES'],
    'articleCert_table_tableCert': [],
    'tableCert_tr_trBeginPro': [],
    'trBeginPro_td_beginProdesc': ['textContent__Iniciante em Programação'],
    'trBeginPro_td_tdBeginProCert': [],
    'tdBeginProCert_a_beginProCert': [
        'href__https://cursos.alura.com.br/degree/certificate/c4214034-a004-44c7-98be-d48d4395d272',
        'target___blank',
        'textContent__Certificado'],
        'trBeginPro_td_certIcon': ['rowSpan__6'],
    'certIcon_img_imgCertIcon': ['src__classes/images/cert-design.svg'],
    'tableCert_tr_trJavaSpringB': [],
    'trJavaSpringB_td_JavaSpringBdesc': ['textContent__Java e Spring Boot 3'],
    'trJavaSpringB_td_tdJavaSpringBCert': [],
    'tdJavaSpringBCert_a_JavaSpringBCert': [
        'href__https://cursos.alura.com.br/degree/certificate/f484da26-7936-4494-85d1-d6dcb75da899',
        'target___blank',
        'textContent__Certificado'],
    'tableCert_tr_trSQL': [],
    'trSQL_td_SQLdesc': ['textContent__SQL com MySQL'],
    'trSQL_td_tdSQLCert': [],
    'tdSQLCert_a_SQLCert': [
        'href__https://cursos.alura.com.br/degree/certificate/bcd642bb-6a0e-4819-a41f-8dc362b1b65d',
        'target___blank',
        'textContent__Certificado'],
    'tableCert_tr_trDP': [],
    'trDP_td_DPdesc': ['textContent__Desenvolvimento Pessoal'],
    'trDP_td_tdDPCert': [],
    'tdDPCert_a_DPCert': [
        'href__https://cursos.alura.com.br/degree/certificate/94a629ca-5a7b-476a-aca5-9a0e06ebbdcf',
        'target___blank',
        'textContent__Certificado'],
    'tableCert_tr_trEmp': [],
    'trEmp_td_Empdesc': ['textContent__Empreendedorismo'],
    'trEmp_td_tdEmpCert': [],
    'tdEmpCert_a_EmpCert': [
        'href__https://cursos.alura.com.br/degree/certificate/7a97a182-106a-4c07-9118-7184cad52601',
        'target___blank',
        'textContent__Certificado'],
    'tableCert_tr_trOCI': [],
    'trOCI_td_OCIdesc': ['textContent__Oracle Cloud Infrastructure'],
    'trOCI_td_tdOCICert': [],
    'tdOCICert_a_OCICert': [
        'href__https://cursos.alura.com.br/degree/certificate/4de0f63c-1784-478e-bf42-f337951b4707',
        'target___blank',
        'textContent__Certificado']
}